### ISSUE TITLE
Doesn't work tutorial code of tensorflow

### ISSUE THREAD

**Issue by takuro-Ishida** [furukawa-laboratory/somf#79]
**target library
Tutorial code that coded by tensorflow.
* som/animal_data/animal_grad_norm_using_tensorflow_som.py
* tsom/animal_data/tensorflow_animal_data_example.py
* tsom/kura_data/tsom_tensorflow_kura_fitting.py

**Describe the bug バグの説明**
Tutorial code that coded by tensor flow doesn't work.
So, please help us @FlowSs .
Please check, debag and report.

**Comment by FlowSs** [comment]
I checked the different files:

Version used tensorflow 1.13.1 (latest stable)

-  tsom/animal_data/tensorflow_animal_data_example.py : There was a problem on the variables regarding BMUs, I modified the name, everything should work now

- tsom/kura_data/tsom_tensorflow_kura_fitting.py : no problem (it works okay for me?)

- som/animal_data/animal_grad_norm_using_tensorflow_som.py : no problem (it works okay for me)

Aside from the tensorflow_animal_data_example.py where the name of variables were wrong, I think the issue come from the __init__.py

@ae14watanabe I think the __init__.py you put into models/ should be deleted because otherwise pycharm will keep importing every libraries in it every time as it is an __init__.py, even if it's not needed.

I had multiple time the error : 'theano module not found' even though I was using only tensorflow.

**Comment by ae14watanabe** [comment]
@FlowSs I understood! Thanks! I will create another issue, and fix it!

**Comment by ae14watanabe** [comment]
@FlowSs Would you create pull request `Fix_#79` ?

**Comment by ae14watanabe** [comment]
@FlowSs Sorry! I dismiss #80 !
